/**
 * AUTO-GENERATED by scripts/sync-couple-questionnaire.ts — do not edit by hand.
 * Source: KELIAA COUPLE™ QUESTIONNAIRE PREMIUM.md (72 questions · 18×4).
 */

export type CoupleDimensionId =
  | "vision_couple"
  | "valeurs"
  | "mariage"
  | "communication"
  | "conflits"
  | "emotions"
  | "affection"
  | "intimite"
  | "finances"
  | "famille"
  | "roles"
  | "decision"
  | "projet_vie"
  | "carriere"
  | "enfants"
  | "autonomie"
  | "spiritualite"
  | "limites"

export type CoupleQuestionType = "LIKERT" | "COUPLE_PERCEPTION"

export type CoupleQuestion = {
  id: string
  dimension: CoupleDimensionId
  text: string
  type: CoupleQuestionType
  /** Si true, un écart fort peut alimenter un flag de vigilance sécurité (sans diagnostic). */
  safetyRelevant?: boolean
}

export const COUPLE_DIMENSION_META: Record<
  CoupleDimensionId,
  { label: string; order: number }
> = {
  vision_couple: { label: "Vision du couple", order: 1 },
  valeurs: { label: "Valeurs fondamentales", order: 2 },
  mariage: { label: "Vision du mariage", order: 3 },
  communication: { label: "Communication", order: 4 },
  conflits: { label: "Gestion des conflits", order: 5 },
  emotions: { label: "Fonctionnement émotionnel", order: 6 },
  affection: { label: "Affection et proximité", order: 7 },
  intimite: { label: "Intimité", order: 8 },
  finances: { label: "Finances", order: 9 },
  famille: { label: "Famille et belle-famille", order: 10 },
  roles: { label: "Rôles conjugaux", order: 11 },
  decision: { label: "Prise de décision", order: 12 },
  projet_vie: { label: "Projet de vie", order: 13 },
  carriere: { label: "Carrière et aspirations", order: 14 },
  enfants: { label: "Enfants et parentalité", order: 15 },
  autonomie: { label: "Autonomie et interdépendance", order: 16 },
  spiritualite: { label: "Spiritualité et convictions", order: 17 },
  limites: { label: "Limites, confiance et sécurité", order: 18 },
}

const LIKERT_OPTIONS = [
  { id: "1", label: "Pas du tout vrai pour moi", value: 1 },
  { id: "2", label: "Plutôt faux pour moi", value: 2 },
  { id: "3", label: "Mitigé / cela dépend", value: 3 },
  { id: "4", label: "Plutôt vrai pour moi", value: 4 },
  { id: "5", label: "Tout à fait vrai pour moi", value: 5 },
] as const

export function getCoupleLikertOptions() {
  return LIKERT_OPTIONS
}

function q(
  id: string,
  dimension: CoupleDimensionId,
  text: string,
  type: CoupleQuestionType = "LIKERT",
  safetyRelevant?: boolean
): CoupleQuestion {
  return { id, dimension, text, type, safetyRelevant }
}

/** Banque active Premium — 72 questions (mêmes items pour les deux participants). */
export const COUPLE_QUESTIONS: CoupleQuestion[] = [
  q("VISION_001", "vision_couple", "Je sais clairement quel type de couple je souhaite construire."),
  q("VISION_002", "vision_couple", "Je considère notre relation comme un véritable projet commun, et pas seulement comme une relation basée sur les sentiments."),
  q("VISION_003", "vision_couple", "Je pense que nous avons aujourd'hui une vision suffisamment proche de ce que nous voulons devenir ensemble."),
  q("VISION_004", "vision_couple", "Je me sens prêt(e) à adapter certaines habitudes personnelles pour construire une vie commune qui nous ressemble."),
  q("VALUES_001", "valeurs", "Nos valeurs fondamentales me semblent compatibles."),
  q("VALUES_002", "valeurs", "Nous avons une conception proche du respect dans une relation."),
  q("VALUES_003", "valeurs", "Nous avons une vision proche de ce que signifient la fidélité et l'engagement."),
  q("VALUES_004", "valeurs", "Je pense que nos valeurs peuvent réellement nous aider à prendre des décisions importantes ensemble."),
  q("MARRIAGE_001", "mariage", "Je sais ce que le mariage représente personnellement pour moi."),
  q("MARRIAGE_002", "mariage", "J'ai des attentes relativement claires concernant les responsabilités de chacun dans le mariage."),
  q("MARRIAGE_003", "mariage", "Je pense que mon/ma partenaire et moi avons une vision suffisamment proche de l'engagement conjugal."),
  q("MARRIAGE_004", "mariage", "Je me sens prêt(e) à construire avec mon/ma partenaire même lorsque certaines périodes de la vie deviennent difficiles."),
  q("COMM_001", "communication", "Je peux dire clairement à mon/ma partenaire ce dont j'ai besoin sans attendre qu'il/elle le devine."),
  q("COMM_002", "communication", "Je me sens réellement écouté(e) lorsque je parle d'un sujet important."),
  q("COMM_003", "communication", "Nous pouvons parler de sujets difficiles sans que la conversation devienne immédiatement une attaque ou une défense."),
  q("COMM_004", "communication", "Même lorsque je suis émotionnellement chargé(e), je peux encore communiquer avec respect."),
  q("CONFLICT_001", "conflits", "Lorsque nous ne sommes pas d'accord, je peux rester dans la conversation sans chercher immédiatement à fuir ou à imposer mon point de vue."),
  q("CONFLICT_002", "conflits", "Je peux entendre le point de vue de mon/ma partenaire même lorsque je ne suis pas d'accord."),
  q("CONFLICT_003", "conflits", "Après une tension, je suis capable de revenir vers mon/ma partenaire pour reprendre le dialogue."),
  q("CONFLICT_004", "conflits", "Je considère qu'un désaccord peut être traversé sans remettre automatiquement en question la solidité de notre relation."),
  q("EMOTION_001", "emotions", "Je comprends assez facilement ce que je ressens lorsque quelque chose me touche dans notre relation."),
  q("EMOTION_002", "emotions", "Je peux expliquer à mon/ma partenaire ce que je ressens sans transformer immédiatement mon émotion en accusation."),
  q("EMOTION_003", "emotions", "Je parviens généralement à retrouver mon calme lorsque je suis contrarié(e) ou frustré(e)."),
  q("EMOTION_004", "emotions", "Lorsque je me sens inquiet/inquiète dans la relation, je sais demander ce dont j'ai besoin."),
  q("AFFECTION_001", "affection", "Je me sens affectivement proche de mon/ma partenaire."),
  q("AFFECTION_002", "affection", "Nous exprimons facilement notre affection l'un envers l'autre."),
  q("AFFECTION_003", "affection", "Je me sens aimé(e) ou considéré(e) dans notre relation."),
  q("AFFECTION_004", "affection", "Je peux parler facilement à mon/ma partenaire de ce dont j'ai besoin pour me sentir proche de lui/elle."),
  q("INTIMACY_001", "intimite", "Je me sens suffisamment à l'aise pour parler de mes attentes concernant l'intimité dans notre relation."),
  q("INTIMACY_002", "intimite", "Je pense que mon/ma partenaire et moi avons une vision suffisamment proche de la place de l'intimité dans notre relation."),
  q("INTIMACY_003", "intimite", "Je me sens libre d'exprimer mes limites concernant l'intimité sans craindre d'être jugé(e)."),
  q("INTIMACY_004", "intimite", "Je pense que nous pouvons parler de nos besoins d'intimité avec respect, écoute et délicatesse."),
  q("FIN_001", "finances", "Je pense que nous avons une vision suffisamment proche de la manière dont l'argent doit être géré dans notre couple."),
  q("FIN_002", "finances", "Je me sens à l'aise avec l'idée de parler ouvertement d'argent, de revenus, de dépenses et de priorités financières."),
  q("FIN_003", "finances", "Pour moi, la sécurité financière doit être suffisamment construite avant certaines grandes étapes de notre vie."),
  q("FIN_004", "finances", "Je pense que nous saurions trouver un équilibre entre les besoins personnels, les projets communs, l'épargne et les dépenses."),
  q("FAMILY_001", "famille", "Je considère qu'une fois engagés sérieusement, certaines décisions doivent appartenir en priorité au couple."),
  q("FAMILY_002", "famille", "Je me sens capable de poser des limites à ma famille lorsque cela devient nécessaire pour protéger notre relation."),
  q("FAMILY_003", "famille", "Je pense que mon/ma partenaire et moi avons une vision suffisamment proche de la place que nos familles doivent occuper dans notre vie."),
  q("FAMILY_004", "famille", "Je pense que nous pouvons gérer une pression familiale sans laisser celle-ci décider à notre place."),
  q("ROLES_001", "roles", "J'ai une idée assez claire de la manière dont les responsabilités devraient être réparties dans notre couple."),
  q("ROLES_002", "roles", "Je pense que mon/ma partenaire et moi avons des attentes compatibles concernant les rôles de chacun."),
  q("ROLES_003", "roles", "Je suis prêt(e) à ajuster ma manière de fonctionner lorsque les circonstances de notre vie changent."),
  q("ROLES_004", "roles", "Je pense que nous saurons discuter de la répartition des responsabilités sans considérer automatiquement cette discussion comme une attaque personnelle."),
  q("DECISION_001", "decision", "Je pense que les grandes décisions doivent être discutées ensemble avant d'être prises."),
  q("DECISION_002", "decision", "Je suis capable de modifier ma position après avoir réellement entendu les arguments de mon/ma partenaire."),
  q("DECISION_003", "decision", "Je me sens respecté(e) dans la manière dont les décisions importantes sont prises dans notre relation."),
  q("DECISION_004", "decision", "Nous pouvons rechercher un accord sans que l'un des deux ait systématiquement besoin de gagner."),
  q("LIFE_PROJECT_001", "projet_vie", "J'ai une vision relativement claire de la vie que je souhaite construire dans les prochaines années."),
  q("LIFE_PROJECT_002", "projet_vie", "Je pense que mon/ma partenaire et moi avons une vision suffisamment proche de notre avenir."),
  q("LIFE_PROJECT_003", "projet_vie", "Nous avons des attentes suffisamment proches concernant les grandes étapes que nous voulons franchir ensemble."),
  q("LIFE_PROJECT_004", "projet_vie", "Je me sens prêt(e) à ajuster certains projets personnels pour construire un projet de vie réellement commun."),
  q("CAREER_001", "carriere", "La place que je souhaite donner à ma carrière est importante pour moi."),
  q("CAREER_002", "carriere", "Je pense que mon/ma partenaire comprend suffisamment mes ambitions professionnelles."),
  q("CAREER_003", "carriere", "Je suis prêt(e) à rechercher un équilibre entre mes ambitions professionnelles et les besoins de notre couple."),
  q("CAREER_004", "carriere", "Je pense que nous saurions nous adapter si la carrière de l'un de nous imposait temporairement des changements importants."),
  q("PARENTING_001", "enfants", "Je sais clairement si je souhaite avoir des enfants dans ma vie."),
  q("PARENTING_002", "enfants", "Je pense que mon/ma partenaire et moi avons une vision suffisamment proche du moment où nous souhaiterions avoir des enfants."),
  q("PARENTING_003", "enfants", "Nous avons des attentes suffisamment compatibles concernant les valeurs que nous voudrions transmettre à nos enfants."),
  q("PARENTING_004", "enfants", "Je pense que nous pourrions discuter de l'éducation, des responsabilités et des règles concernant nos enfants sans nous opposer systématiquement."),
  q("AUTONOMY_001", "autonomie", "Je suis à l'aise avec le fait que mon/ma partenaire ait certaines activités ou certains espaces qui lui appartiennent personnellement."),
  q("AUTONOMY_002", "autonomie", "J'ai besoin de conserver une part de temps personnel même lorsque notre relation devient très engagée."),
  q("AUTONOMY_003", "autonomie", "Je peux être proche de mon/ma partenaire sans avoir besoin de tout faire avec lui/elle."),
  q("AUTONOMY_004", "autonomie", "Je respecte facilement le besoin d'espace personnel de mon/ma partenaire lorsqu'il/elle en exprime le besoin."),
  q("SPIRIT_001", "spiritualite", "Mes convictions spirituelles ou personnelles occupent une place importante dans ma manière de construire ma relation."),
  q("SPIRIT_002", "spiritualite", "Je pense que mon/ma partenaire et moi avons une vision suffisamment proche des convictions ou valeurs qui doivent guider notre foyer."),
  q("SPIRIT_003", "spiritualite", "Je souhaite que nos convictions puissent influencer certaines décisions importantes de notre vie commune."),
  q("SPIRIT_004", "spiritualite", "Je pense que nous pouvons respecter nos différences de convictions sans que celles-ci deviennent une source permanente de tension."),
  q("SECURITY_001", "limites", "Je me sens respecté(e) dans mes limites personnelles au sein de notre relation.", "LIKERT", true),
  q("SECURITY_002", "limites", "Je peux exprimer clairement mon désaccord ou mon refus sans craindre d'être humilié(e) ou dévalorisé(e).", "LIKERT", true),
  q("SECURITY_003", "limites", "Je considère que la confiance entre nous repose sur suffisamment de transparence et de fiabilité.", "LIKERT", true),
  q("SECURITY_004", "limites", "Je me sens globalement en sécurité pour être moi-même dans cette relation.", "LIKERT", true),
]

export function getCoupleQuestions() {
  return COUPLE_QUESTIONS
}

export function getCoupleQuestionCount() {
  return COUPLE_QUESTIONS.length
}
