/**
 * Catalogue ressources V1 — sous-ensemble Bibliothèque KELIAA Couple.
 */

import type { CatalogResource, DomainTag } from "@/lib/couple/engine/types"
import type { CoupleDimensionId } from "@/lib/couple/questionBank"

export const RESOURCE_CATALOG_VERSION = "1.0.0"

export function dimensionToDomain(dim: CoupleDimensionId): DomainTag {
  const map: Partial<Record<CoupleDimensionId, DomainTag>> = {
    communication: "communication",
    conflits: "conflits",
    finances: "finances",
    famille: "famille",
    mariage: "mariage",
    intimite: "intimite",
    valeurs: "valeurs",
    projet_vie: "projets",
    decision: "decision",
    limites: "confiance",
    affection: "affection",
    emotions: "emotions",
    enfants: "enfants",
    roles: "roles",
    autonomie: "autonomie",
    carriere: "carriere",
    spiritualite: "spiritualite",
    vision_couple: "connexion",
  }
  return map[dim] ?? "connexion"
}

export const RESOURCE_CATALOG: CatalogResource[] = [
  {
    id: "COUPLE-COM-001",
    version: "1.0.0",
    title: "Ce que j’aimerais que tu comprennes",
    format: "exercice",
    kind: "pratique",
    domain: "communication",
    domains: ["communication", "connexion"],
    tags: ["besoin_clarification", "priorite_elevee"],
    minOffer: "essential",
    duration: "25–35 min",
    objective: "Mettre des mots précis sur un besoin sans accuser.",
    why: "Quand la communication frotte, écrire puis reformuler réduit les malentendus.",
    steps: [
      "Chacun écrit 8 minutes : ce que je vis, ce que je crains, ce dont j’ai besoin.",
      "Lecture à tour de rôle (3 min max), sans interruption.",
      "L’autre reformule uniquement : « Ce que j’entends, c’est… »",
      "Notez une seule chose concrète à essayer cette semaine.",
    ],
    questions: [
      "Qu’est-ce qui m’a touché(e) ?",
      "Quelle demande puis-je formuler sans attaquer ?",
    ],
    incompatibleWith: [],
  },
  {
    id: "COUPLE-CON-001",
    version: "1.0.0",
    title: "Réparer après friction",
    format: "exercice",
    kind: "pratique",
    domain: "conflits",
    domains: ["conflits", "connexion"],
    tags: ["besoin_reconnexion", "forte_difference"],
    minOffer: "essential",
    duration: "15–20 min",
    objective: "Installer un rituel de réparation après tension.",
    why: "Sans réparation, même un petit écart laisse une trace.",
    steps: [
      "Chacun dit : « Ce que j’ai ressenti » (pas « ce que tu as fait »).",
      "Chacun reconnaît une part de responsabilité, même petite.",
      "Formulez une réparation concrète.",
      "Convenez d’un signal de pause pour la prochaine fois.",
    ],
    questions: [
      "Qu’est-ce qui m’a blessé(e) vraiment ?",
      "De quoi ai-je besoin pour me sentir à nouveau en sécurité ?",
    ],
    incompatibleWith: [],
  },
  {
    id: "COUPLE-FIN-001",
    version: "1.0.0",
    title: "Trois règles d’argent pour 90 jours",
    format: "exercice",
    kind: "pratique",
    domain: "finances",
    domains: ["finances", "decision"],
    tags: ["besoin_structure", "ecart_important", "priorite_elevee"],
    minOffer: "essential",
    duration: "40 min",
    objective: "Rendre visibles seuils, peurs et autonomies autour de l’argent.",
    why: "Les tensions financières naissent souvent de règles implicites.",
    steps: [
      "Répondez séparément aux questions ci-dessous.",
      "Comparez sans juger.",
      "Rédigez 3 règles : seuil commun, marge personnelle, date de revue.",
    ],
    questions: [
      "À partir de quel montant décidons-nous ensemble ?",
      "Qu’est-ce qui me rassure avant une dépense importante ?",
      "Quelle marge d’autonomie est importante pour moi ?",
    ],
    incompatibleWith: [],
  },
  {
    id: "COUPLE-PRJ-001",
    version: "1.0.0",
    title: "Calendrier à deux — 6 / 12 / 24 mois",
    format: "exercice",
    kind: "pratique",
    domain: "projets",
    domains: ["projets", "mariage", "enfants"],
    tags: ["besoin_structure", "ecart_important"],
    minOffer: "essential",
    duration: "35 min",
    objective: "Transformer les visions générales en étapes datées.",
    why: "Sans dates, l’un attend et l’autre presse.",
    steps: [
      "Chacun note ses étapes souhaitées à 6, 12 et 24 mois.",
      "Comparez : ce qui est commun, ce qui diverge, ce qui est négociable.",
      "Choisissez une seule étape à clarifier sous 14 jours.",
    ],
    questions: [
      "Quelles étapes sont non négociables pour moi dans les 24 mois ?",
      "Qu’est-ce qui doit être vrai avant la prochaine étape ?",
    ],
    incompatibleWith: [],
  },
  {
    id: "COUPLE-ENF-001",
    version: "1.0.0",
    title: "Parler enfants / parentalité sans pression",
    format: "exercice",
    kind: "pratique",
    domain: "enfants",
    domains: ["enfants", "projets"],
    tags: ["ecart_important", "priorite_elevee"],
    minOffer: "essential",
    duration: "30 min",
    objective: "Clarifier désir, timing et conditions avec respect.",
    why: "Ce sujet structure le couple ; le flou blesse.",
    steps: [
      "Chacun écrit : désir, timing, conditions.",
      "Lecture croisée sans interruption.",
      "Fixez une date pour en reparler (pas « on verra »).",
    ],
    questions: [
      "Est-ce que je veux des enfants ? Dans quel horizon ?",
      "Quelles conditions sont indispensables pour moi ?",
    ],
    incompatibleWith: [],
  },
  {
    id: "COUPLE-AFF-001",
    version: "1.0.0",
    title: "Un geste d’affection cette semaine",
    format: "exercice",
    kind: "pratique",
    domain: "affection",
    domains: ["affection", "connexion"],
    tags: ["ecart_modere", "besoin_clarification"],
    minOffer: "essential",
    duration: "10 min + pratique",
    objective: "Traduire l’affection en comportements concrets.",
    why: "Un écart d’affection se vit souvent comme un manque d’amour.",
    steps: [
      "Chacun cite 2 gestes qui le font se sentir aimé(e).",
      "Chacun choisit 1 geste à offrir 3 fois cette semaine.",
      "Point court dimanche : qu’est-ce qui a changé ?",
    ],
    questions: ["Quels gestes me font me sentir aimé(e) ?"],
    incompatibleWith: [],
  },
  {
    id: "COUPLE-DEC-001",
    version: "1.0.0",
    title: "Décider si on décide aujourd’hui ou plus tard",
    format: "exercice",
    kind: "pratique",
    domain: "decision",
    domains: ["decision", "projets"],
    tags: ["besoin_structure", "ecart_modere"],
    minOffer: "essential",
    duration: "20 min",
    objective: "Cadre pour les désaccords de rythme décisionnel.",
    why: "Sans cadre, l’un se sent freiné, l’autre poussé.",
    steps: [
      "Nommez le sujet unique.",
      "Décidez ensemble : on tranche ce soir, ou on se donne X jours.",
      "Si blocage : qui tranche temporairement, jusqu’à quand ?",
    ],
    questions: ["Sur quels sujets ai-je besoin de plus de temps ?"],
    incompatibleWith: [],
  },
  {
    id: "COUPLE-LIM-001",
    version: "1.0.0",
    title: "Cinq limites non négociables",
    format: "exercice",
    kind: "pratique",
    domain: "confiance",
    domains: ["confiance"],
    tags: ["priorite_elevee", "forte_difference"],
    minOffer: "essential",
    duration: "25 min",
    objective: "Rendre le « non » audible des deux côtés.",
    why: "Les limites protégent le couple ; elles ne sont pas de la froideur.",
    steps: [
      "Chacun écrit 5 limites personnelles.",
      "Partagez sans débat la première fois.",
      "Repérez 1 limite commune à protéger cette semaine.",
    ],
    questions: ["Qu’est-ce qui franchit une limite pour moi ?"],
    incompatibleWith: [],
  },
  {
    id: "COUPLE-CAR-001",
    version: "1.0.0",
    title: "Carte — 10 minutes sur ce qui nous unit",
    format: "carte",
    kind: "conversation",
    domain: "connexion",
    domains: ["connexion", "valeurs"],
    tags: ["forte_convergence"],
    minOffer: "essential",
    duration: "10 min",
    objective: "Nommer une force avant de parler d’un écart.",
    why: "Commencer par les appuis change le climat.",
    steps: [
      "Chacun cite une chose qu’il apprécie chez l’autre cette semaine.",
      "Chacun cite une force du couple.",
    ],
    questions: ["Qu’est-ce qui nous unit concrètement en ce moment ?"],
    incompatibleWith: [],
  },
  {
    id: "COUPLE-CAR-002",
    version: "1.0.0",
    title: "Carte — reformuler avant de répondre",
    format: "carte",
    kind: "conversation",
    domain: "communication",
    domains: ["communication"],
    tags: ["besoin_clarification", "ecart_modere"],
    minOffer: "essential",
    duration: "5–10 min",
    objective: "Pratiquer la reformulation sur un sujet sensible.",
    why: "Être compris précède souvent le fait d’être d’accord.",
    steps: [
      "A parle 90 secondes.",
      "B reformule uniquement.",
      "Inversez.",
    ],
    questions: ["Ai-je été entendu(e) ?"],
    incompatibleWith: [],
  },
  {
    id: "COUPLE-CAR-003",
    version: "1.0.0",
    title: "Carte — argent sans procès",
    format: "carte",
    kind: "conversation",
    domain: "finances",
    domains: ["finances"],
    tags: ["besoin_structure", "ecart_important"],
    minOffer: "essential",
    duration: "10 min",
    objective: "Ouvrir le sujet argent sans humiliation.",
    why: "Nommer une peur d’argent apaise souvent plus qu’un budget parfait.",
    steps: [
      "Chacun dit une peur liée à l’argent.",
      "Chacun dit ce qui le rassurerait.",
    ],
    questions: ["Qu’est-ce qui me rassure vraiment ?"],
    incompatibleWith: [],
  },
  {
    id: "COUPLE-CAR-004",
    version: "1.0.0",
    title: "Carte — signal de pause",
    format: "carte",
    kind: "conversation",
    domain: "conflits",
    domains: ["conflits"],
    tags: ["besoin_reconnexion"],
    minOffer: "essential",
    duration: "5 min",
    objective: "Choisir un signal de pause commun.",
    why: "Le silence sans date nourrit l’abandon ; la pause datée protège.",
    steps: [
      "Proposez un mot ou geste de pause.",
      "Fixez une durée minimale avant reprise (ex. 20 min).",
    ],
    questions: ["Quel signal ne sera pas vécu comme un rejet ?"],
    incompatibleWith: [],
  },
  {
    id: "COUPLE-FIC-001",
    version: "1.0.0",
    title: "Fiche — check-in hebdomadaire",
    format: "fiche",
    kind: "reflexion",
    domain: "connexion",
    domains: ["connexion", "communication"],
    tags: ["forte_convergence", "besoin_reconnexion"],
    minOffer: "essential",
    duration: "15 min / semaine",
    objective: "Une joie, une friction, une demande, une gratitude.",
    why: "La régularité bat l’intensité sporadique.",
    steps: [
      "Bloquez 15 min un jour fixe.",
      "Chacun : une joie, une friction, une demande, une gratitude.",
    ],
    questions: ["Qu’est-ce qui a bougé cette semaine ?"],
    incompatibleWith: [],
  },
  {
    id: "COUPLE-FIC-002",
    version: "1.0.0",
    title: "Fiche — décision à deux",
    format: "fiche",
    kind: "reflexion",
    domain: "decision",
    domains: ["decision", "finances", "projets"],
    tags: ["besoin_structure"],
    minOffer: "essential",
    duration: "20 min",
    objective: "Options, critères, délai, qui tranche temporairement.",
    why: "Écrire le cadre évite de tout rejouer à chaque décision.",
    steps: [
      "Écrire le sujet.",
      "Lister options et critères.",
      "Fixer délai et mode de tranchage temporaire.",
    ],
    questions: ["Qui tranche si on bloque — jusqu’à quand ?"],
    incompatibleWith: [],
  },
  {
    id: "COUPLE-FIC-003",
    version: "1.0.0",
    title: "Fiche — réparation",
    format: "fiche",
    kind: "reflexion",
    domain: "conflits",
    domains: ["conflits"],
    tags: ["besoin_reconnexion"],
    minOffer: "essential",
    duration: "15 min",
    objective: "Ce que j’ai fait / ce que ça a produit / ce que je propose / ce dont j’ai besoin.",
    why: "Structurer la réparation évite le cessez-le-feu vide.",
    steps: [
      "Remplir les 4 cases chacun.",
      "Lire à tour de rôle.",
      "Choisir une réparation concrète.",
    ],
    questions: ["La réparation a-t-elle ramené de la chaleur ?"],
    incompatibleWith: [],
  },
  {
    id: "COUPLE-FIC-004",
    version: "1.0.0",
    title: "Fiche — vision de foyer",
    format: "fiche",
    kind: "reflexion",
    domain: "projets",
    domains: ["projets", "mariage", "enfants"],
    tags: ["preparation_mariage", "besoin_structure"],
    minOffer: "essential",
    duration: "25 min",
    objective: "Clarifier ce que « avancer ensemble » signifie concrètement.",
    why: "Les mots génériques (« bientôt », « on verra ») entretiennent la frustration.",
    steps: [
      "Écrire chacun sa vision en 10 lignes.",
      "Souligner les points communs.",
      "Circler 1 point à clarifier sous 14 jours.",
    ],
    questions: ["Qu’est-ce qui est négociable / non négociable ?"],
    incompatibleWith: [],
  },
  {
    id: "COUPLE-PRO-001",
    version: "1.0.0",
    title: "Protocole — conversation difficile (25–30 min)",
    format: "protocole",
    kind: "progression",
    domain: "communication",
    domains: ["communication", "conflits"],
    tags: ["priorite_elevee", "besoin_reconnexion"],
    minOffer: "premium_plus",
    duration: "25–30 min",
    objective: "Traverser un sujet sensible sans dérive.",
    why: "Un cadre chronométré protège le lien quand l’intensité monte.",
    steps: [
      "Cadre (2 min) : un sujet, téléphones de côté.",
      "Tour A puis tour B (5 min chacun).",
      "Reformulation croisée (5 min).",
      "Une demande concrète chacun (3 min).",
      "Micro-engagement daté (2 min).",
      "Si tension : pause 20 min, puis reprise du protocole.",
    ],
    questions: ["Avons-nous terminé les 5 étapes sans humiliation ?"],
    incompatibleWith: [],
    premiumPlus: true,
  },
  {
    id: "COUPLE-PRO-002",
    version: "1.0.0",
    title: "Protocole — cycle de conflit",
    format: "protocole",
    kind: "progression",
    domain: "conflits",
    domains: ["conflits"],
    tags: ["besoin_reconnexion", "forte_difference"],
    minOffer: "premium_plus",
    duration: "3 sessions / 14 jours",
    objective: "Repérer et assouplir la boucle approche / retrait.",
    why: "Le motif qui se répète compte plus que « qui a commencé ».",
    steps: [
      "Session 1 : décrire le cycle sans accuser.",
      "Session 2 : tester le signal de pause une fois.",
      "Session 3 : noter ce qui a changé et ce qui reste.",
    ],
    questions: ["Quel est notre cycle typique en une phrase ?"],
    incompatibleWith: ["COUPLE-PRO-001"],
    premiumPlus: true,
  },
  {
    id: "COUPLE-PRO-003",
    version: "1.0.0",
    title: "Protocole — construire des accords",
    format: "protocole",
    kind: "progression",
    domain: "projets",
    domains: ["projets", "finances", "decision"],
    tags: ["besoin_structure", "preparation_mariage"],
    minOffer: "premium_plus",
    duration: "2 × 40 min",
    objective: "Passer de visions générales à accords écrits datés.",
    why: "Un accord écrit bat la bonne intention floue.",
    steps: [
      "Lister les sujets à accorder (max 3).",
      "Pour chacun : règle, durée, date de revue.",
      "Relire à voix haute et dater.",
    ],
    questions: ["Cet accord est-il tenable pour chacun ?"],
    incompatibleWith: [],
    premiumPlus: true,
  },
  {
    id: "COUPLE-SUI-001",
    version: "1.0.0",
    title: "Suivi 7 jours — une priorité",
    format: "suivi",
    kind: "suivi",
    domain: "connexion",
    domains: ["connexion"],
    tags: ["priorite_elevee"],
    minOffer: "premium_plus",
    duration: "7 jours",
    objective: "Tenir une seule action liée à la priorité n°1.",
    why: "Une priorité tenue vaut dix intentions.",
    steps: [
      "J1 : écrire l’action.",
      "J3 : point de 5 min.",
      "J7 : ce qui a bougé / ce qu’on ajuste.",
    ],
    questions: ["Avons-nous tenu l’action au moins 5 jours sur 7 ?"],
    incompatibleWith: [],
    premiumPlus: true,
  },
]

export function getResourceById(id: string): CatalogResource | undefined {
  return RESOURCE_CATALOG.find((r) => r.id === id)
}
